### PR TITLE
Create adminer flavour

### PR DESCRIPTION
**Pull request by Sidicer**
> Adminer (formerly phpMinAdmin) is a full-featured database management tool written in PHP. Conversely to phpMyAdmin, it consist of a single file ready to deploy to the target server.  
> Adminer is available for MySQL, PostgreSQL, SQLite and Oracle.

This is a non-nomad persistent jail.

To modify which databases can `adminer` connect to - edit `adminer.sh L:85` and remove the ones you do not need:

```sh
step "Install PHP database extensions"
pkg install -y php82-mysqli php82-odbc php82-pgsql php82-pdo_sqlite
```

### CODE REVIEW

**Comment by bretton** [comment]
Awesome stuff @Sidicer , however, I don't think it's ready yet for the potluck repo and website.

Is there a config file for adminer? It would need to be configured with passed in values on pot startup. Check out the README of various flavours. 

For potluck images everything must be passed in as a value and the container 'just run'.

Separately, I have nginx and php config done as follows in the nginx-nomad-alt flavour and a few others.

See
https://github.com/bsdpot/potluck/blob/master/nginx-nomad-alt/nginx-nomad-alt.d/local/share/cook/bin/configure-nginx.sh

and
https://github.com/bsdpot/potluck/blob/master/nginx-nomad-alt/nginx-nomad-alt.d/local/share/cook/bin/configure-php.sh

we also include consul, node_exporter, syslog-ng integration in all flavours for monitoring purposes, for tight integration with beast-of-argh flavour, or the various independent flavours with prometheus, loki, grafana etc. 

The following example playbook for a virtual datacenter gives an idea of how it all works together
https://codeberg.org/Honeyguide/ansible-pot-foundation

**Comment by Sidicer** [comment]
Thank you @bretton for the reply. I have redone the whole adminer flavour as per your request. I highly referenced `redis-single` flavour, as well as `nginx-nomad-alt` to match your configuration.

As per your question if "adminer has any configuration?": No. Adminer is so good because it's a single `.php` file deployment not needing any configuration. But I have added the ability to set login credentials and auto-login on page load

**Comment by bretton** [comment]
> As per your question if "adminer has any configuration?": No. Adminer is so good because it's a single `.php` file deployment not needing any configuration. But I have added the ability to set login credentials and auto-login on page load

great stuff @Sidicer looks good, however, I have a few nitpicks:

1. versioning needs a tweak

check the file `CHECKLIST.md` in different flavour directories

in `CHANGELOG.md` use 0.1 or 0.2 or 1.5 etc, however in `$flavour.ini` use 0.1.1 or 0.2.1 or 1.5.9 etc.

So in `adminer.ini` update `version = "0.1-1"` to `version = "0.1.1"`

2. In `CHECKLIST.md` for your flavour, make sure to leave a note of files to update when versions need to be edited on updates, for example `adminer/adminer.d/local/share/cook/bin/configure-adminer.sh` has `v4.8.1/editor-4.8.1.php` and `v4.8.1/adminer-4.8.1.php`.

Someone else updating the image won't know about it and needs attention drawn to it, or you might forget if multiple pot images to maintain.

Updates to images happen on a regular basis for new versions of packages, or new base image for layered images (most).

3. Update all nginx-related files to use `/usr/local/www/adminer` instead of `/usr/local/www/stdwebsite`

4. Adjust `adminer.sh` to install packages individually, so split the following into individual lines

```
step "Install PHP extensions"
pkg install -y php82-mbstring php82-zlib php82-curl php82-gd php82-extensions

step "Install PHP database extensions"
pkg install -y php82-mysqli php82-odbc php82-pgsql php82-pdo_sqlite
```

When updating phpXX packages it makes it easier to fix missing packages when testing builds by commenting out a broken one.

**Comment by Sidicer** [comment]
- Checklist added
- Versioning fixed
- Nginx location altered

Do you think that creating a second flavour `adminer-nomad` would be as simple as copying the current `adminer` flavour and modifying `RUNS_IN_NOMAD` to `true`? As I've kept all of the `RUNS_IN_NOMAD` checks in the cook scripts.

**Comment by bretton** [comment]
> Do you think that creating a second flavour `adminer-nomad` would be as simple as copying the current `adminer` flavour and modifying `RUNS_IN_NOMAD` to `true`? As I've kept all of the `RUNS_IN_NOMAD` checks in the cook scripts.

Well done on updates. Off the top of my head you'll need a `$flavour+4` file with contents `set-cmd -c "/usr/local/bin/cook"`

see

https://github.com/bsdpot/potluck/blob/master/nextcloud-nginx-nomad/nextcloud-nginx-nomad%2B4

https://github.com/bsdpot/potluck/blob/master/nginx-s3-ssl-nomad/nginx-s3-ssl-nomad%2B4

**Comment by bretton** [comment]
build test had errors, then fixed, now builds completely, will merge and once built, have an image up at potluck distribution site.

**Comment by bretton** [comment]
https://potluck.honeyguide.net/blog/adminer/

**Comment by Sidicer** [comment]
Thank you @bretton! And yes, in regards of `copy-in-flv` it's probably part of potman, and not `pot`, as I was testing these builds with `potbuilder` and `pottery` guests from [Potman](https://github.com/bsdpot/potman)

**Pull request merged**
