### PR TITLE
hashicluster: Catch up with recent developments

### PR DESCRIPTION
**Pull request by grembo**

### CODE REVIEW

**Comment by bretton** [comment]
@grembo do you want to update versions of loki and promtail?

from beast-of-argh image
```
step "Download loki release from github"
fetch -qo - https://github.com/grafana/loki/releases/download/\
v2.9.4/loki-freebsd-amd64.zip | unzip -p - loki-freebsd-amd64 \
  >/usr/local/bin/loki
chmod 755 /usr/local/bin/loki

if [ "$(sha256 -q /usr/local/bin/loki)" != \
  "65893a34be52b1ab1368e4b39bd042ba3831782ff0bcf8ed549cd111d5262756" ]; then
  exit_error "/usr/local/bin/loki checksum mismatch!"
fi

step "Download promtail release from github"
fetch -qo - https://github.com/grafana/loki/releases/download/\
v2.9.4/promtail-freebsd-amd64.zip | unzip -p - promtail-freebsd-amd64 \
  >/usr/local/bin/promtail
chmod 755 /usr/local/bin/promtail

if [ "$(sha256 -q /usr/local/bin/promtail)" != \
  "e7b2ee7c3a78a5a72dd3952febf141cf6514ff8aa35f4c97be637aad9d027e20" ]; then
  exit_error "/usr/local/bin/promtail checksum mismatch!"
fi
```

**Comment by grembo** [comment]
Hi @bretton,

I would do that in a separate update after deploying and testing updated versions.

Cheers

**Comment by grembo** [comment]
Thanks!

**Comment by bretton** [comment]
images built

**Pull request merged**
