### PR TITLE
First commit for MinIO pot

### PR DESCRIPTION
**Pull request by ebarriosjr**
Signed-off-by: ebarrios <esteban.barrios@trivago.com>

Created template for MinIO pot.
MinIO is a High Performance Object Storage released under Apache License v2.0.
https://min.io/

### CODE REVIEW

**Comment by hny-gd** [comment]
Thank you very much, your contribution is very much appreciated! :-)

**Comment by hny-gd** [comment]
Image now available at https://potluck.honeyguide.net/blog/minio-nomad/

**Comment by ebarriosjr** [comment]
> Image now available at [potluck.honeyguide.net/blog/minio-nomad](https://potluck.honeyguide.net/blog/minio-nomad/)

Just FYI @hny-gd the endpoint does not work. I get redirected to https://honeyguide.eu/blog/minio-nomad/ and get a 404

**Comment by hny-gd** [comment]
Thanks for the heads up, web proxy configuration error, should work now

**Pull request merged**
